[profile.default]
src = "src"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read-write", path = "./deployment.json"}]

[rpc_endpoints]
eth-sepolia = "${RPC_ETH_SEPOLIA}"
base-sepolia = "${RPC_BASE_SEPOLIA}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
